version: '3.9'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playground
      MYSQL_USER: productService
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-volumes/mysql:/docker-entrypoint-initdb.d
    networks:
      - app
volumes:
  mysql_data:
  grafana_data:
networks:
  app:
